- mafic/errors.py
- mafic/node.py
- mafic/playlist.py
- mafic/plugin.py
- mafic/track.py
- mafic/typings/misc.py
Stops using `**` for passing data to classes, since adding fields is not a breaking change (lavalink v4).
> refactor: remove ** abuse

- mafic/__init__.py
- mafic/errors.py
- mafic/node.py
- mafic/player.py
- mafic/plugin.py
- mafic/pool.py
- mafic/region.py
- mafic/stats.py
- mafic/strategy.py
- test_bot/bot/__main__.py
- test_bot/docker-compose.yml
- test_bot/lavalink/Dockerfile
This PR adds location, shard, usage and random node selection. It also supports custom selection functions.
> feat: add node selection/balancing

- mafic/player.py
- pyproject.toml
This PR locks pyright to a specific version. This means that CI will fail...controllably, instead of a change causing it to fail.
> ci: lock pyright to 1.1.279

- .flake8
- mafic/__init__.py
- mafic/errors.py
- mafic/events.py
- mafic/node.py
- mafic/player.py
- mafic/typings/http.py
- mafic/typings/incoming.py
- mafic/typings/misc.py
> feat: add event dispatching

- .readthedocs.yml
- mafic/__libraries.py
Report from @Kraots <https://canary.discord.com/channels/864563184919773226/1075508816914960384/1075510719350571069>.
```py
Traceback (most recent call last):
File "/home/Kraots/okiyu/main.py", line 17, in <module>
import mafic
File "/home/Kraots/venv/lib/python3.10/site-packages/mafic/__init__.py", line 13, in <module>
from . import __libraries
File "/home/Kraots/venv/lib/python3.10/site-packages/mafic/__libraries.py", line 92, in <module>
from disnake.types.gateway import (
File "/home/Kraots/venv/lib/python3.10/site-packages/disnake/types/gateway.py", line 11, in <module>
from .audit_log import AuditLogEntry
File "/home/Kraots/venv/lib/python3.10/site-packages/disnake/types/audit_log.py", line 17, in <module>
from .channel import ChannelType, PermissionOverwrite, VideoQualityMode
File …
```
> fix(libraries): use TYPE_CHECKING to resolve import loop in disnake

- mafic/node.py
From `Cattosarus` on [Discord](https://canary.discord.com/channels/864563184919773226/1074660965347504190/1075015900652109824)
```py
14.02.2023 13:26:07 | ERROR | An HTTP error occured: {"timestamp":1676373968330,"status":404,"error":"Not Found","message":"Not Found","path":"/v3/v3/loadtracks"} (404)
Traceback (most recent call last):
File "C:\Users\Cattosarus\Desktop\mafic-bot\cogs\music.py", line 89, in play
results = await player.fetch_tracks(query)
File "C:\Users\Cattosarus\AppData\Local\Programs\Python\Python39\lib\site-packages\mafic\player.py", line 457, in fetch_tracks
return await node.fetch_tracks(query, search_type=raw_type)
File "C:\Users\Cattosarus\AppData\Local\Programs\Python\Python39\lib\site-packages\mafic\node.py", line 891, in fetch_tracks
data: TrackLoadingResult = …
```
> fix(node): stop appending /v3 if done already

- mafic/player.py
Add `Player.paused` property to expose the current paused state.
> feat(player): expose Player.paused

- mafic/pool.py
This PR alters `NodePool` to not store unavailable nodes.
```py
14.02.2023 13:19:06 | WARNING | Unable to use best node, player not connected, finding random node.
14.02.2023 13:19:06 | ERROR | No nodes found for the region, defaulting to all nodes.
```
> fix(pool): ignore unavailable nodes

- mafic/player.py
- test_bot/bot/__main__.py
Set a blank filter if no filters are applied and are updated.
<https://canary.discord.com/channels/864563184919773226/1076074968087011409/1076074968087011409>
```py
17.02.2023 11:26:46 | INFO | Cattosarus#0463 ran application command "bassboost"
Ignoring exception in command <nextcord.application_command.SlashApplicationCommand object at 0x00000140A183F700>:
Traceback (most recent call last):
File "C:\Users\Cattosarus\AppData\Local\Programs\Python\Python39\lib\site-packages\nextcord\application_command.py", line 863, in invoke_callback_with_hooks
await self(interaction, *args, **kwargs)
File "c:\Users\Cattosarus\Desktop\mafic-bot\cogs\music.py", line 258, in bassboost
await player.remove_filter("bassboost")
File "C:\Users\Cattosarus\AppData\Local\Programs\Python\Python39\lib\site-packages\ …
```
> fix(player): set blank filter if no filters enabled

- mafic/node.py
Should resolve all issues like the following:
```py
Ignoring exception in command <nextcord.application_command.SlashApplicationCommand object at 0x0000012B6C8E06A0>:
Traceback (most recent call last):
File "C:\Users\Cattosarus\AppData\Local\Programs\Python\Python39\lib\site-packages\nextcord\application_command.py", line 863, in invoke_callback_with_hooks
await self(interaction, *args, **kwargs)
File "c:\Users\Cattosarus\Desktop\mafic-bot\cogs\music.py", line 319, in destroy
await player.destroy()
File "C:\Users\Cattosarus\AppData\Local\Programs\Python\Python39\lib\site-packages\mafic\player.py", line 430, in destroy
await self._node.destroy(guild_id=self.guild.id)
File "C:\Users\Cattosarus\AppData\Local\Programs\Python\Python39\lib\site-packages\mafic\node.py", line 871, in __request …
```
> fix(node): ignore no content responses

- .github/workflows/lint.yml
- mafic/filter.py
- pyproject.toml
This allows more types to be passed to `Equalizer` and `Filter`.
This has the side effect of adding `__slots__` to `Equalizer` and `Filter`, since
dataclasses don't support `__slots__` in <3.10.
> feat(filter): allow more types for Equalizer

- mafic/player.py
Add `Player.has_filter`, a way to check if a filter is enabled in that `Player`.
> feat(player): add has_filter method

- mafic/node.py
URL encode `identifier` when querying a track. This fixes an issue where
track names with spaces would not be found.
> fix(node): urlencode query

- mafic/stats.py
- mafic/typings/common.py
Lavalink V4 uses `None` instead of ommitability for `frameStats`.
```
03.05.2023 23:58:16 | DEBUG | Creating task to handle websocket message.
03.05.2023 23:58:16 | DEBUG | Event data: {'frameStats': None, 'players': 1, 'playingPlayers': 1, 'uptime': 423901, 'memory': {'free': 928557288, 'used': 145184536, 'allocated': 1073741824, 'reservable': 1073741824}, 'cpu': {'cores': 4, 'systemLoad': 0.0564602352167119, 'lavalinkLoad': 0.026292104868414472}, 'op': 'stats'}
03.05.2023 23:58:16 | DEBUG | Received event with op stats
03.05.2023 23:58:18 | DEBUG | Received message from websocket.
03.05.2023 23:58:18 | DEBUG | Creating task to handle websocket message.
03.05.2023 23:58:18 | ERROR | Task exception was never retrieved
future: <Task finished name='Task-68' coro=<Node._handle_msg() done, …
```
> fix(stats); check if frame stats is None

- mafic/player.py
- test_bot/bot/__main__.py
`Player.connected` may be `False` but still be in the client's dictionary if it failed to connect.
One example is trying to connect a player where the bot cannot join due to user limits in the channel.
> fix(player): Player.connected being False sometimes

- mafic/node.py
- mafic/player.py
Pass `str` to `Player.play`/`Player.update` to play using an `identifier`.
> feat(player): support str for playing identifiers

- mafic/player.py
This fixes a regression in 2.4.0 where `.current` is not set before sending an API request.
This meant that on lavalink v3, a full track object could not be found sometiems when the event was recieved.
> fix(player): pre-emptively update .current if v3

- mafic/node.py
v4 decode_tracks uses `info` embedded instead of a track info by itself.
> fix(node): fix decode_track parsing

- docs/api/events.rst
- mafic/node.py
Add `on_node_stats` that is dispatched every time a node's stats are received. This is for the purpose of updating and dispatching updates to metrics servers or other internal state.
> fead(node): add on_node_stats

- mafic/node.py
- mafic/player.py
- mafic/pool.py
- test_bot/.dockerignore
- test_bot/bot/__main__.py
- test_bot/docker-compose.multi-node.yml
This is impressive that it even works.
`NodePool.remove_node` has been added, which has a `transfer_players` keyword argument, which:
- `False`: destroys all players
- `True`: `Player.transfer_to` with the best node per player
`Player.transfer_to` tries its best to:
- Fetch existing player state from old node
- Remove player from internal old node state
- Add player to internal new node state
- Tell the new node about our voice config (endpoint, session id, token)
- Update the new player with track, position, volume, pause, filter
`Node.close` was also added to disconnect and cleanup an old node, called in `NodePool.remove_node`
> feat: transfer players to new nodes

- mafic/player.py
No need for a separate method. This should mean that when the bot is disconnected by a moderator, the player is still destroyed.
> feat(player): destroy in disconnect

- mafic/stats.py
Fixed uptime. 
Lavalink is giving milliseconds, but not seconds.
> fix(stats): use ms in uptime over seconds

- LICENSE
HAPPY NEW YEAR!!!! (:trollface:)
This adds the `-present` suffix to the year so that the license still applies to the current year.
> chore(LICENSE): add `present` suffix to year

- mafic/player.py
Fix Player.connect() does not wait until Player._connected became True
```python
player = await voice_channel.connect(cls=Player)
print(player.is_connected())
```
> fix(player): fix Player._connected isn't True after Player.connect()

- docs/api/events.rst
- mafic/node.py
- mafic/pool.py
Add `on_node_unavailable` that is dispatched when `Node.available` become `False`
Modify NodePool.nodes to return only available nodes, preventing players from attempting to connect to unavailable nodes.
Fix doesn't wait for ready `Node.connect` when reconnecting to the node.
> feat(node): support unavailable node handling

- .github/workflows/lint.yml
- .readthedocs.yml
- mafic/__libraries.py
Fix poetry install returning "poetry: export:command not found" error. Also applies the configuration addition from #119, thanks @spifory!
> docs(rtd): fix poetry install
